### ISSUE TITLE
Hard coded URLs to the back end server

### ISSUE THREAD

**Issue by grange85** [nationalarchives/tna-long-form-template#1]
There are hard-coded URLs pointing at pages.testlb.nationalarchives.gov.uk - these links need to be root relative as they will not work externally (and actually won't work at all now the site is at btarchives.testlb...)

**Comment by grange85** [comment]
There are (currently) eight hard-coded references to pages.testlb (I believe related to lazyloading)
see (view-source:http://test.nationalarchives.gov.uk/first-world-war/telecommunications-in-war)

**Comment by punalsc** [comment]
From what we have seen, the content has been copied over from pages.testlb.nationalarchives.gov.uk to btarchives.livelb.nationalarchives.gov.uk.

**Comment by punalsc** [comment]
@grange85 can we close this issue?
